// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnwGC6R-1BFcriK2VIB4DT2ZglNIj8zyE',
    appId: '1:1010444431273:web:6007189f27ca6c1f1c5eb8',
    messagingSenderId: '1010444431273',
    projectId: 'activity-point-monitor-77be6',
    authDomain: 'activity-point-monitor-77be6.firebaseapp.com',
    storageBucket: 'activity-point-monitor-77be6.appspot.com',
    measurementId: 'G-VEZVXBMGJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1NkkIulcbPwmjJbDSXMiRzL1aAVckYhw',
    appId: '1:1010444431273:android:101810c43a2a171a1c5eb8',
    messagingSenderId: '1010444431273',
    projectId: 'activity-point-monitor-77be6',
    storageBucket: 'activity-point-monitor-77be6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ6Q0_mKTEeb9KjrHJLg-JIC-o17_R4Lc',
    appId: '1:1010444431273:ios:48cdff305edcf5a91c5eb8',
    messagingSenderId: '1010444431273',
    projectId: 'activity-point-monitor-77be6',
    storageBucket: 'activity-point-monitor-77be6.appspot.com',
    iosClientId: '1010444431273-1m971grt6t4887h9431o04193a3aere2.apps.googleusercontent.com',
    iosBundleId: 'com.example.activityPointMonitoringProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ6Q0_mKTEeb9KjrHJLg-JIC-o17_R4Lc',
    appId: '1:1010444431273:ios:48cdff305edcf5a91c5eb8',
    messagingSenderId: '1010444431273',
    projectId: 'activity-point-monitor-77be6',
    storageBucket: 'activity-point-monitor-77be6.appspot.com',
    iosClientId: '1010444431273-1m971grt6t4887h9431o04193a3aere2.apps.googleusercontent.com',
    iosBundleId: 'com.example.activityPointMonitoringProject',
  );
}
